### ISSUE TITLE
Error while refereshing the browser

### ISSUE THREAD

**Issue by SaiAravind112** [lamoglia/publish-aggregation#3]
Exception in onStop callback: TypeError: handle.stop is not a function
I20180712-20:20:26.251(5.5)?     at Subscription.self.onStop (packages/lamoglia:publish-aggregation/lib/aggregator.js:220:12)
I20180712-20:20:26.251(5.5)?     at runWithEnvironment (packages/meteor.js:1241:24)
I20180712-20:20:26.252(5.5)?     at packages/meteor.js:1254:14
I20180712-20:20:26.252(5.5)?     at packages/ddp-server/livedata_server.js:1155:7
I20180712-20:20:26.252(5.5)?     at Array.forEach (<anonymous>)
I20180712-20:20:26.252(5.5)?     at Function._.each._.forEach (packages/underscore.js:139:11)
I20180712-20:20:26.252(5.5)?     at Subscription._callStopCallbacks (packages/ddp-server/livedata_server.js:1154:7)
I20180712-20:20:26.253(5.5)?     at Subscription._deactivate (packages/ddp-server/livedata_server.js:1144:10)
I20180712-20:20:26.253(5.5)?     at packages/ddp-server/livedata_server.js:893:11
I20180712-20:20:26.253(5.5)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20180712-20:20:26.253(5.5)?     at Session._deactivateAllSubscriptions (packages/ddp-server/livedata_server.js:892:7)
I20180712-20:20:26.254(5.5)?     at packages/ddp-server/livedata_server.js:450:12
I20180712-20:20:26.254(5.5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
I20180712-20:20:26.254(5.5)?     at packages/meteor.js:505:25
I20180712-20:20:26.254(5.5)?     at runWithEnvironment (packages/meteor.js:1241:24)

- 

- [ ] 

`const pipelineCreator = () => ([
  { $group: { _id: { productName: '$productName' }, count: { $sum: 1 } } },
]);

const options = {
  collectionName: 'clientuser',
  transform: (doc) => ({ ...doc, productName: doc._id.productName }),
  singleValueField: 'count'
};

Meteor.publish('message.counts.by.sender', buildAggregator(UserLogging, pipelineCreator, options));
`

**Comment by tquiroga** [comment]
Same error when using a simple example like the one on the documentation. It's strange, in the code it looks fine, `handle.stop()` should not be called as by default the option is set to false.

However, if you set `observeChangesFilter: false` in your options, the error goes away. 

EDIT: Actually it's still there

**Comment by mbessieres** [comment]
In my mind the issue is pretty straight-forward. At the end of aggregator.js we check if updateFilter is truthy before calling `updateFilter.stop()` but we do not check if handle is truthy before calling `handle.stop()`.

```js
    if (updateHandle) {
        updateHandle.stop();
    }
    handle.stop();
```

`handle` only gets set if `observeChangesFilter` is truthy and it is false by default.

Is anyone taking a look at this or would you prefer a PR?

**Comment by lamoglia** [comment]
Thanks @mbessieres a PR would be great.
